<?php

namespace Winze\PageBuilderBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends DocumentRepository
{
}