<?php

namespace Winze\PageBuilderBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends DocumentRepository {

    public function findAllPartern() {
        return $this->dm->createQueryBuilder('WinzePageBuilderBundle:Menu')
                        ->field('menuPatern')->equals(null)
                        ->sort('position', 'asc')
                        ->getQuery()
                        ->execute();
    }
    
    public function findAllParternActif() {
        return $this->dm->createQueryBuilder('WinzePageBuilderBundle:Menu')
                        ->field('menuPatern')->equals(null)
                        ->field('isActif')->equals(true)
                        ->sort('position', 'asc')
                        ->getQuery()
                        ->execute();
    }
}