<?php

namespace Winze\PageBuilderBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends DocumentRepository {
    public function findAllPartern(){
        return $this->dm->createQueryBuilder('WinzePageBuilderBundle:Page')
                        ->field('pagePatern')->equals(null)
                        ->getQuery()
                        ->execute();
    }
}