# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
WinzeBackendBundle:
    resource: "@WinzeBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin
WinzeSelectLanguage:
    type:     annotation
    pattern: /
    defaults:  { _controller: WinzeFrontendBundle:Language:index }    
WinzeFrontendBundle:
    pattern:   /{_locale}/{path}/
    defaults:  { _controller: WinzeFrontendBundle:Frontend:path }    
    requirements:
        _locale: en|fr
        path: ".+"
WinzeFrontendHomeBundle:
    resource: "@WinzeFrontendBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr